### PR TITLE
Upgraded to dbt-core 1.4.

### LINKED ISSUE #122: upgrade to support dbt-core v1.4.0
## Background

The latest version of dbt Core,`dbt-core==1.4.0`, was published on January 25, 2023 ([PyPI](https://pypi.org/project/dbt-core/1.4.0/) | [Github](https://github.com/dbt-labs/dbt-core/releases/tag/v1.4.0)). In fact, a patch, `dbt-core==1.4.1` ([PyPI](https://pypi.org/project/dbt-core/1.4.1/) | [Github](https://github.com/dbt-labs/dbt-core/releases/tag/v1.4.1)), was also released on the same day.

## How to upgrade

https://github.com/dbt-labs/dbt-core/discussions/6624 is an open discussion with more detailed information. If you have questions, please put them there! https://github.com/dbt-labs/dbt-core/issues/6849 is for keeping track of the community's progress on releasing 1.4.0

The above linked guide has more information, but below is a high-level checklist of work that would enable a successful 1.4.0 release of your adapter. 

- [ ] support Python 3.11 (only if your adapter's dependencies allow)
- [ ] Consolidate timestamp functions & macros
- [ ] Replace deprecated exception functions
- [ ] Add support for more tests

## the next minor release: 1.5.0

FYI, `dbt-core==1.5.0` is expected to be released at the end of April. Please plan on allocating a more effort to upgrade support compared to previous minor versions. Expect to hear more in the middle of April.

At a high-level expect much greater adapter test coverage (a very good thing!), and some likely heaving renaming and restructuring as the API-ification of dbt-core is now well underway. See https://github.com/dbt-labs/dbt-core/milestone/82 for more information.

### PR DESCRIPTION
**Pull request by lpezet**
resolves #122 

### Description

Upgrading to dbt-core 1.4:
- now using `field()` from  *dataclasses* package for policy fields definition. Consequently updated code to then use `get_default_include_policy()` to access class field
- using DbtRuntimeError instead of RuntimeException
- using FailedToConnectError instead of FailedToConnectException
- using dbt.exceptions.DbtDatabaseError instead of dbt.exceptions.DatabaseException
- updated `requirements-dev.txt` to use dbt-core 1.4.latest
- using dbt.exceptions.CompilationError instead of deprecated [dbt.exceptions.raise_compiler_error](https://github.com/dbt-labs/dbt-core/blob/v1.4.6/core/dbt/exceptions.py#L2276-L2282) 

### Checklist
 - [x] I have run this code in development and it appears to resolve the stated issue
 - [x] This PR includes tests, or tests are not required/relevant for this PR
 - [x] I have updated the `CHANGELOG.md` with information about my change

### CODE REVIEW

**Comment by lpezet** [comment]
@dbeatty10 Not sure whether this project is still (even if sporadically) maintained but I'm in need to using dbt-mysql with dbt-core 1.4.
I'm having issues getting the docker-compose up and running (it starts but then each db says something is already running on their 3306 port) and I haven't figured out how to fix that yet.
Having sait that, the following tests pass:
- Unit tests
- Functional tests PASS for **mysql**. I'm having some weird issue with **mysql5** (some "TypeError: replace_dict() missing 1 required positional argument: 'dct'" errors). I haven't tested with **mariadb**.

**Review by moszutij — COMMENTED** [review]
It could be beneficial to substitute the deprecated function [dbt.exceptions.raise_compiler_error](https://github.com/dbt-labs/dbt-core/blob/v1.4.6/core/dbt/exceptions.py#L2276-L2282) with dbt.exceptions.CompilationError in the */impl.py files.

**Comment by dbeatty10** [comment]
🚀 Thank you for your work here @lpezet !

I won't be able to spend time this week on reviewing this, but can give it a review next week.

**Comment by lpezet** [comment]
@moszutij Thanks. I just made those changes. Weird my VSCode didn't catch those...
@dbeatty10 Awesome! Thx!

**Comment by BamboOSZ** [comment]
👀

**Comment by wesen** [comment]
I was just trying this one out @lpezet , and I think dbt.exceptions.DatabaseException needs to be updated to dbt.exceptions.DbtDatabaseError. I haven't done a deeper dive, just running my setup through it.

**Comment by wesen** [comment]
@lpezet I use intellij idea/pycharm, but in this case just saw it by... writing bad SQL :)

**Comment by uraurora** [comment]
Why this pr not being merged? Any progress now?

**Review by dbeatty10 — APPROVED** [review]
Thank you @lpezet!

**Comment by lucasfcnunes** [comment]
I can't find the 1.4 release

**Comment by outinim** [comment]
Why is the 1.4 version is not linked to the main branch ? cc @dbeatty10 🙏🏼 
What do you need to update the release ?

**Pull request merged**
